[package]
name = "hologram-lang_en"
provides = [ "hologram-lang" ]
conflicts = [ "hologram-lang_de", "hologram-lang_no" ]
version = "5.0.0"
release = 1
description = "english locales"

[[file]]
path = "/etc/X11/xorg.conf.d/00-keyboard.conf"
mode = "0644"
contentFrom = "files/keyboard.conf_hologram-lang_en"
