[package]
name = "holodeck-luv"
version = "4.0.0"
release = 1
description = "configuration of laptop 'luv'"
requires = [
	"holo-users-groups",

	"hologram-base-arch",
	"hologram-dev",
	"hologram-multimedia",

	"android-file-transfer",
	"dhcpcd",
	"intel-ucode",
	"iwd",
	"openssh",
	"xorg-xrandr", # for peripheral screens
]


# user

[[group]]
name = "sudo"
system = false

[[user]]
name    = "laerling"
system  = false
comment = "Benjamin Ludwig"
uid     = 1000
groups  = [ "audio", "video", "sudo" ]
home    = "/home/laerling"
shell   = "/bin/bash"

[[directory]]
path = "/home/laerling"
mode = "0700"
owner = "laerling"
group = "laerling"


# network

# enable iwd
[[symlink]]
path = "/etc/systemd/system/multi-user.target.wants/iwd.service"
target = "/usr/lib/systemd/system/iwd.service"

# enable dhcpcd
[[symlink]]
path = "/etc/systemd/system/multi-user.target.wants/dhcpcd.service"
target = "/usr/lib/systemd/system/dhcpcd.service"


# screen setup

[[file]]
path = "/usr/share/holo/files/99-laptop/etc/X11/xinit/xinitrc.holoscript"
mode = "0755"
contentFrom = "holoscripts/xinitrc.pl"

[[file]]
path = "/usr/share/holo/files/99-laptop/etc/systemd/logind.conf.holoscript"
mode = "0755"
contentFrom = "holoscripts/logind.conf.sh"


# storage and mount points

[[file]]
path = "/usr/share/holo/files/99-laptop/etc/fstab.holoscript"
mode = "0755"
contentFrom = "holoscripts/fstab.sh"

[[directory]]
path = "/mnt/archive"
mode = "0700"
owner = 1000
group = 1000

# mount points for USB ports, because why not

[[directory]]
path = "/mnt/usb0"
mode = "0700"
owner = 1000
group = 1000

[[directory]]
path = "/mnt/usb1"
mode = "0700"
owner = 1000
group = 1000

[[directory]]
path = "/mnt/usb2"
mode = "0700"
owner = 1000
group = 1000
