[package]
name = "hologram-lang_no"
provides = [ "hologram-lang" ]
conflicts = [ "hologram-lang_de", "hologram-lang_en" ]
version = "5.1"
release = 1
description = "norwegian locales"
requires = [
]

[[file]]
path = "/etc/X11/xorg.conf.d/00-keyboard.conf"
mode = "0644"
contentFrom = "keyboard.conf_hologram-lang_no"

[[file]]
path = "/etc/vconsole.conf"
mode = "0644"
contentFrom = "vconsole.conf_hologram-lang_no"
