[package]
name = "hologram-base"
version = "4.1.0"
release = 1
description = "Minimal configuration for all systems"
requires = [
	"holo",
	"group:base-devel", # don't depend on group:base. It can't be resolved by pacman -Sg

	"acpi",
	"holo",
	"screen",
	"tree",
	"unzip",
	"vim", # contains gvim
	# emacs in hologram-dev since it is too big for a minimal installation
	# intel-ucode/intel-microcode in holodecks since it is machine specific
]


[[group]]
name = "sudo"
system = false

[[file]]
path = "/etc/sudoers.d/sudo"
mode = "0444"
contentFrom = "files/sudo"

[[file]]
path = "/usr/share/holo/files/00-base/etc/bash.bashrc.holoscript"
mode = "0755"
contentFrom = "holoscripts/bashrc"
