[package]
name = "hologram-dev"
version = "1.12"
release = 1
description = "packages and configuration for software development"
requires = [
	"hologram-gui",

	"bc",
	"ed",
	"emacs",
	"gdb",
	"git",
	"go",
	"go-tools",
	"gvim",
	"nmap",
	"rust",
	"tk", # for gitk
]


# emacs

[[file]]
path = "/usr/bin/emacsd"
mode = "0755"
contentFrom = "files/emacsd"
# don't make a shortcut called ed because that would shadow another awesome text editor!

[[file]]
path = "/usr/bin/emacsq"
mode = "0755"
contentFrom = "files/emacsq"

[[symlink]]
path = "/usr/bin/eq"
target = "/usr/bin/emacsq"


[[file]]
path = "/etc/profile.d/hologram-dev.sh"
mode = "0755"
contentFrom = "files/profile_hologram-dev"


# git

[[file]]
path = "/etc/gitconfig"
mode = "0644"
contentFrom = "files/gitconfig"
