[package]
name = "hologram-gui"
version = "3.3.1"
release = 1
description = "X configuration without desktop environment"
requires = [

  # graphics drivers have to be included in holodecks

	# X
	"group:xorg-apps",
	"xorg-server",
	"xorg-xinit",

	# desktop environment
	"hologram-desktop",
	# don't depend on hologram-dm, because the desktop environment
	# hologram should know whether it needs a DM. E. g. i3 does
	# not necessarily need one.

	# locales
	"hologram-lang",

	# programs independent of desktop environment
	"scrot",
	"xsel",
]


[[file]]
path = "/usr/share/holo/files/01-gui/etc/inputrc.holoscript"
mode = "0755"
contentFrom = "files/inputrc.sed"
