[package]
name = "hologram-video"
version = "2.2.0"
release = 1
description = "Video programs and codecs"
requires = [
	"hologram-gui",

	# copyright stuff
	"libdvdread",
	"libdvdcss",
	"libdvdnav",

	"mpv",
	"youtube-dl",
	"vlc" # can play some files/DVDs that mpv can't. Also, good title selection for DVDs.
]

[[file]]
path = "/usr/bin/yt"
mode = "0755"
contentFrom = "files/yt"

[[file]]
path = "/usr/bin/yta"
mode = "0755"
contentFrom = "files/yta"

[[file]]
path = "/usr/bin/ytmp4"
mode = "0755"
contentFrom = "files/ytmp4"

[[file]]
path = "/usr/bin/dl"
mode = "0755"
contentFrom = "files/dl"

[[file]]
path = "/usr/bin/dla"
mode = "0755"
contentFrom = "files/dla"
