[package]
name = "hologram-base-arch"
version = "1.10.0"
release = 1
description = "Minimal configuration, specific to Arch Linux"
requires = [
  #############################################################
  # dependencies whose package names exist only in Arch repos #
  #############################################################
  "base", # 'base' package replaces group 'base'
  "bind-tools", # for host, dig, nslookup
  "gnu-netcat",
  "group:base-devel",
  "man-pages", # linux manpages (putchar, ...)
  # no yaourt because that can't be installed as root (due to
  # makepkg), therefore it cannot exist when a holodeck is
  # installed for the first time

  ##############################################################
  # dependencies that have the same package name on Arch and   #
  # Debian, but which I don't need on my debian-based machines #
  # so far                                                     #
  ##############################################################
  "acpi",
  "cryptsetup",
  "rsync",

  # and of course, hologram-base itself
  "hologram-base",
]


[[file]]
path = "/usr/share/holo/files/01-base-arch/etc/pacman.d/mirrorlist.holoscript"
mode = "0755"
contentFrom = "holoscripts/mirrorlist"

[[file]]
path = "/usr/share/holo/files/01-base-arch/etc/bash.bashrc.holoscript"
mode = "0755"
contentFrom = "holoscripts/bashrc_hologram-base-arch"

# disable account locking when entering password wrong
[[file]]
path = "/usr/share/holo/files/00-base-arch/etc/security/faillock.conf.holoscript"
mode = "0755"
contentFrom = "holoscripts/faillock.conf"

# enable multilib
[[file]]
path = "/usr/share/holo/files/00-base-arch/etc/pacman.conf.holoscript"
mode = "0755"
contentFrom = "holoscripts/pacman.conf"
