[package]
name = "hologram-graphics"
version = "2.0.4"
release = 1
description = "graphics and drawing programs"
requires = [
	"hologram-gui",

	"evince",
	"graphviz",
	"kolourpaint",
  "breeze-icons", # icons for kolourpaint
]
