[package]
name = "hologram-desktop-i3"
version = "1.6.0"
release = 1
provides = [ "hologram-desktop" ]
description = "i3 wm and basic desktop utilities. Can be installed alongside any hologram-desktop-*"
requires = [

	# console
	"guake",

	# window manager (with status bar and application starter)
	"xorg-server",
	"xorg-xinit",
	"xorg-xrandr", # for configuring peripheral screens etc.
	"i3-wm",
	"i3status",
	"dmenu",

	# fonts
	"gnu-free-fonts", # replaces ttf-freefont
	"adobe-source-code-pro-fonts",

	# standard programs depending on GUI
	"slock",
	"scrot",
]


[[file]]
path = "/usr/share/holo/files/01-gui/etc/i3/config"
mode = "0755"
contentFrom = "files/i3_config"

[[file]]
path = "/etc/X11/xinit/xinitrc.d/hologram-desktop-i3"
mode = "0644"
contentFrom = "files/xinitrc_hologram-desktop-i3"


# own binaries

[[file]]
path = "/usr/bin/x"
mode = "0755"
content = "startx"

[[file]]
path = "/usr/bin/exiti3"
mode = "0755"
contentFrom = "files/exiti3"

[[file]]
path = "/usr/bin/slocksus"
mode = "0755"
contentFrom = "files/slocksus"

[[file]]
path = "/usr/bin/slockhib"
mode = "0755"
contentFrom = "files/slockhib"

[[file]]
path = "/usr/bin/scrots"
mode = "0755"
contentFrom = "files/scrots"
