[package]
name = "hologram-lang_de"
provides = [ "hologram-lang" ]
conflicts = [ "hologram-lang_en", "hologram-lang_no" ]
version = "4.0"
release = 1
description = "german locales"
requires = [
]

[[file]]
path = "/etc/X11/xorg.conf.d/00-keyboard.conf"
mode = "0644"
contentFrom = "files/keyboard.conf_hologram-lang_de"

[[file]]
path = "/etc/vconsole.conf"
mode = "0644"
contentFrom = "files/vconsole.conf_hologram-lang_de"
