[package]
name = "hologram-studio-audio"
version = "1.0.0"
release = 1
description = "Audio production software"
requires = [
	"hologram-gui",
	"hologram-audio",

  # Good read: https://wiki.archlinux.org/index.php/Professional_audio
  "group:pro-audio",
]

# needs restart, followed by manual reinstallation of this hologram
[[action]]
on = "setup"
script = "modprobe snd-seq-midi"

[[action]]
on = "cleanup"
script = "modprobe -r snd-seq-midi"
