[package]
name = "hologram-desktop-cinnamon"
version = "1.0.1"
release = 1
provides = [ "hologram-desktop" ]
conflicts = [
	"hologram-desktop-gnome",
	"hologram-desktop-i3",
	]
description = "cinnamon desktop environment"
requires = [

	# desktop environment
	"cinnamon",

	# display manager
	"hologram-dm",

	# standard programs depending on GUI
	"scrot",
]


[[file]]
path = "/etc/X11/xinit/xinitrc.d/cinnamon"
mode = "0755"
contentFrom = "files/xinitrc_hologram-desktop-cinnamon"
