[package]
name = "hologram-graphics"
version = "2.2.0"
release = 1
description = "graphics and drawing programs"
requires = [
	"hologram-gui",

	"evince",
	"feh",
	"graphviz",
	"kolourpaint",
	"breeze-icons", # icons for kolourpaint
]

[[file]]
path = "/usr/local/bin/feh"
mode = "0755"
content = "/usr/bin/feh --scale-down $@"
