[package]
name = "hologram-base"
version = "4.0.3"
release = 1
description = "Minimal configuration for all systems"
requires = [
	"acpi",
	"holo",
	"screen",
	"tree",
	"unzip",
	"vim", # contains gvim
	# emacs in hologram-dev since it is too big for a minimal installation
	# intel-ucode/intel-microcode in holodecks since it is machine specific
]


[[file]]
path = "/etc/sudoers.d/hologram-base"
mode = "0444"
contentFrom = "files/sudoers"

[[file]]
path = "/usr/share/holo/files/00-base/etc/bash.bashrc.holoscript"
mode = "0755"
contentFrom = "holoscripts/bashrc"
