[package]
name = "hologram-multimedia"
version = "1.0"
release = 1
description = "Bundle with video, graphics, audio, communication, and games"
requires = [
	"hologram-audio",
	"hologram-communication",
	"hologram-graphics",
	"hologram-video",
]
