[package]
name = "hologram-multimedia"
version = "1.4"
release = 1
description = "Bundle with video, graphics, audio, communication, and games"
requires = [
	"hologram-audio",
	"hologram-communication",
	"hologram-graphics",
	"hologram-video",
]

[[file]]
path = "/etc/mpv/mpv.conf"
mode = "0644"
content = "audio-display=no"
