[package]
name = "hologram-dm-gdm"
version = "1.0.0"
release = 1
provides = [ "hologram-dm" ]
conflicts = [ "hologram-dm-startx" ]
description = "The GDM Gnome Display Manager"
requires = [
	"hologram-gui",
	"gdm",
]


# enable gdm
[[symlink]]
path = "/etc/systemd/system/display-manager.service"
target = "/usr/lib/systemd/system/gdm.service"

