[package]
name = "hologram-lang_no"
provides = [ "hologram-lang" ]
version = "2.2"
release = 1
description = "norwegian locales for X"
requires = [
]

[[file]]
path = "/etc/X11/xorg.conf.d/00-keyboard.conf"
mode = "0644"
contentFrom = "keyboard.conf"

[[file]]
path = "/etc/vconsole.conf"
mode = "0644"
contentFrom = "vconsole.conf"
