[package]
name = "hologram-lang_en"
provides = [ "hologram-lang" ]
version = "3.0"
release = 1
description = "english locales"
requires = [
]

[[file]]
path = "/etc/X11/xorg.conf.d/00-keyboard.conf"
mode = "0644"
contentFrom = "keyboard.conf"
