[package]
name = "holodeck-archvm"
version = "0.1"
release = 1
description = "configuration of arch VM"
requires = [
	"holo-users-groups",

	"hologram-base",

	"openssh",
]


# user

[[user]]
name    = "laerling"
system  = false
comment = "Benjamin Ludwig"
uid     = 1001
groups  = [ "audio", "video", "wheel" ]
home    = "/home/laerling"
shell   = "/bin/bash"

[[directory]]
path = "/home/laerling"
mode = "0700"
owner = 1001
group = 1001


# networking

# dhcp
[[symlink]]
# as created by `systemctl enable dhcpcd`
path = "/etc/systemd/system/multi-user.target.wants/dhcpcd.service"
target = "/usr/lib/systemd/system/dhcpcd.service"

# DNS
[[symlink]]
# as created by `systemctl enable systemd-resolved`
path = "/etc/systemd/system/dbus-org.freedesktop.resolve1.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"
[[symlink]]
# as created by `systemctl enable systemd-resolved`
path = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"
