[package]
name = "hologram-communication"
version = "1.5"
release = 1
description = "communication programs (for use with a GUI)"
requires = [
	"hologram-gui",

	"discord", # don't forget to turn off notifications (libnotify is not installed)
	"firefox",
	"hexchat",
	"irssi",
	"thunderbird",
]
