[package]
name = "hologram-communication"
version = "1.0"
release = 1
description = "communication programs (for use with a GUI)"
requires = [
	"hologram-gui",

	"firefox",
	"hexchat",
	"irssi",
	"telegram-desktop",
]
