[package]
name = "hologram-video"
version = "1.4"
release = 1
description = "Video programs and codecs"
requires = [
	"hologram-gui",

	# copyright stuff
	"libdvdread",
	"libdvdcss",
	"libdvdnav",

	"mpv",
	"youtube-dl",
	"vlc" # can play some files/DVDs that mpv can't. Also, good title selection for DVDs.
]

[[file]]
path = "/usr/bin/yt"
mode = "0555"
content = """
#!/usr/bin/bash
mpv --ytdl-format=mp4 $(xsel -b)
"""

[[file]]
path = "/usr/bin/ythd"
mode = "0555"
content = """
#!/usr/bin/bash
mpv $(xsel -b)
"""