[package]
name = "hologram-desktop-i3"
version = "1.0.0"
release = 1
provides = [ "hologram-desktop" ]
conflicts = [
	"hologram-desktop-cinnamon",
	"hologram-desktop-kde",
	]
description = "i3 wm and basic desktop utilities"
requires = [

	# console
	"guake",

	# window manager (with status bar and application starter)
	"i3-wm",
	"i3status",
	"dmenu",

	# fonts
	"gnu-free-fonts", # replaces ttf-freefont
	"adobe-source-code-pro-fonts",

	# standard programs depending on GUI
	"evince",
	"slock",
	"kolourpaint",
	"scrot",
	"feh",
	"xsel",
]


[[file]]
path = "/usr/share/holo/files/01-gui/etc/i3/config"
mode = "0755"
contentFrom = "i3_config"

[[file]]
path = "/usr/share/holo/files/01-gui/etc/X11/xinit/xinitrc.holoscript"
mode = "0755"
contentFrom = "xinitrc.pl"


# own binaries

[[file]]
path = "/usr/bin/x"
mode = "0755"
content="""
#!/bin/bash
startx
"""

[[file]]
path = "/usr/bin/exiti3"
mode = "0755"
contentFrom = "exiti3"

[[file]]
path = "/usr/bin/slocksus"
mode = "0755"
contentFrom = "slocksus"

[[file]]
path = "/usr/bin/slockhib"
mode = "0755"
contentFrom = "slockhib"

[[file]]
path = "/usr/bin/scrots"
mode = "0755"
contentFrom = "scrots"
