[package]
name = "hologram-dm-startx"
version = "1.0.0"
release = 1
provides = [ "hologram-dm" ]
conflicts = [
	"hologram-dm-gdm",
	]
description = "Not an actual display manager, but startx with x binary"
requires = [
	"hologram-gui",
]


[[file]]
path = "/usr/bin/x"
mode = "0755"
content="""
#!/bin/bash
startx
"""
