[package]
name = "hologram-dev"
version = "1.6"
release = 1
description = "packages and configuration for software development"
requires = [
	"hologram-gui",

	"ed",
	"emacs",
	"gdb",
	"git",
	"go",
	"gvim",
	"nmap",
	"rust",
	"bc",
]


# emacs

[[file]]
path = "/usr/bin/emacsd"
mode = "0755"
contentFrom = "emacsd.sh"
# don't make a shortcut called ed because that would shadow another awesome text editor!

[[file]]
path = "/usr/bin/emacsq"
mode = "0755"
contentFrom = "emacsq.sh"

[[symlink]]
path = "/usr/bin/eq"
target = "/usr/bin/emacsq"


[[file]]
path = "/usr/share/holo/files/02-dev/etc/bash.bashrc.holoscript"
mode = "0755"
contentFrom = "bash.bashrc.pl"


# git

[[file]]
path = "/etc/gitconfig"
mode = "0644"
contentFrom = "gitconfig"
