[package]
name = "holodeck-laptop"
version = "1.25"
release = 1
description = "configuration of laptop"
requires = [
	"holo-users-groups",

	"hologram-base",
	"hologram-dev",
	"hologram-multimedia",

	"android-file-transfer",
	"intel-ucode",
	"wpa_supplicant",
	"xorg-xrandr", # for peripheral screens
]


# user

[[user]]
name    = "laerling"
system  = false
comment = "Benjamin Ludwig"
uid     = 1001
groups  = [ "audio", "video", "wheel" ]
home    = "/home/laerling"
shell   = "/bin/bash"

[[directory]]
path = "/home/laerling"
mode = "0700"
owner = 1001
group = 1001


# screen setup

[[file]]
path = "/usr/share/holo/files/99-laptop/etc/X11/xinit/xinitrc.holoscript"
mode = "0755"
contentFrom = "xinitrc.pl"


# networking

# dhcp
[[symlink]]
# as created by `systemctl enable dhcpcd`
path = "/etc/systemd/system/multi-user.target.wants/dhcpcd.service"
target = "/usr/lib/systemd/system/dhcpcd.service"

# DNS
[[symlink]]
# as created by `systemctl enable systemd-resolved`
path = "/etc/systemd/system/dbus-org.freedesktop.resolve1.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"
[[symlink]]
# as created by `systemctl enable systemd-resolved`
path = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

# WLAN
[[file]]
path = "/etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf"
contentFrom = "wpa_supplicant-wlp2s0.conf"
[[symlink]]
# as created by `systemctl enable wpa_supplicant@wlp2s0`
path = "/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp2s0.service"
target = "/usr/lib/systemd/system/wpa_supplicant@.service"


# mount points

[[directory]]
path = "/mnt/backup"
mode = "0700"
owner = 1001
group = 1001

[[directory]]
path = "/mnt/archive"
mode = "0700"
owner = 1001
group = 1001

# mount points for USB ports, because why not

[[directory]]
path = "/mnt/usb0"
mode = "0700"
owner = 1001
group = 1001

[[directory]]
path = "/mnt/usb1"
mode = "0700"
owner = 1001
group = 1001

[[directory]]
path = "/mnt/usb2"
mode = "0700"
owner = 1001
group = 1001
